apiVersion: v1
kind: Service
metadata:
  name: toystore-backend
  labels:
    app: toystore-backend
spec:
  selector:
    app: toystore-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}