apiVersion: apps/v1
kind: Deployment
metadata:
  name: toystore-backend
  labels:
    app: toystore-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: toystore-backend
  template:
    metadata:
      labels:
        app: toystore-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:{{ .Values.backend.service.port }}"