apiVersion: apps/v1
kind: Deployment
metadata:
  name: toystore-db
  labels:
    app: toystore-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toystore-db
  template:
    metadata:
      labels:
        app: toystore-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{.Values.database.name}}
            - name: POSTGRES_USER
              value: {{.Values.database.user}}
            - name: POSTGRES_PASSWORD
              value: {{.Values.database.password}}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{.Values.database.user}}
                - -d
                - {{.Values.database.name}}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{.Values.database.user}}
                - -d
                - {{.Values.database.name}}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: postgres-storage
          emptyDir: {}
