apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toystore-db-pvc
  labels:
    app: toystore-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}