apiVersion: v1
kind: Service
metadata:
  name: toystore-frontend
  labels:
    app: toystore-frontend
spec:
  type: LoadBalancer
  selector:
    app: toystore-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}