apiVersion: apps/v1
kind: Deployment
metadata:
  name: toystore-frontend
  labels:
    app: toystore-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: toystore-frontend
  template:
    metadata:
      labels:
        app: toystore-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.frontend.service.port }}