name: "sustainable_toystore"

services:
  # .NET Backend
  toystore-backend:
    image: ghcr.io/clue2-sose25/sustainable_toystore/toystore-backend:latest
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DOCKER_BUILDKIT: 1

  # React frontend
  toystore-frontend:
    image: ghcr.io/clue2-sose25/sustainable_toystore/toystore-frontend:latest
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - toystore-backend
    environment:
      DOCKER_BUILDKIT: 1