#example values for running the toystore SUT
sutConfigFileName: toystore.yaml
sutConfig: |
  config:
    sut: "toystore"
    namespace: "toystore"
    sut_git_repo: "https://github.com/clue2-sose25/sustainable_toystore"
    sut_path: "toystore"
    helm_chart_path: "toystore/toystore"
    values_yaml_name: "values.yaml"
    target_service_name: "teastore-webui"
    application_endpoint_path: "/tools.descartes.teastore.webui"
    default_resource_limits:
      cpu: 1000
      memory: 1024
    wait_before_workloads: 120
    wait_after_workloads: 120
  workloads:
    - name: "shaped"
      description: "Workload with custom load shape behavior."
      timeout_duration: 120
      workload_runtime: 64
      workload_settings: {}
      locust_files:
        - "sut_configs/workloads/toystore/locustfile.py"
  resource_limits: []
  variants:
    - name: "baseline"
      description: "A ToyStore application storing its data in a local SQLite DB"
      target_branch: "baseline"
      colocated_workload: true
      critical_services: ["toystore-frontend", "toystore-backend"]
      autoscaling: "cpu"
    - name: "postgres"
      description: "A ToyStore application using external Postgres DB"
      target_branch: "postgres"
      colocated_workload: true
      critical_services: ["toystore-frontend", "toystore-backend", "toystore-db"]
      autoscaling: "cpu"
clueConfig: |
  config:
    experiment_timeout: 150
    prometheus_url: "http://clue-cluster-control-plane:30090"
    docker_registry_address: ghcr.io/clue2-sose25//sustainable_toystore
    local_public_ip: "registry"
    local_port: 5000
    remote_platform_arch: "linux/arm64/v8"
    local_platform_arch: "linux/arm64/v8"
    target_utilization: 70
clueDeployer:
  env:
    SUT: toystore
    VARIANTS: baseline
    WORKLOADS: shaped
    DEPLOY_ONLY: "false"
    N_ITERATIONS: "1"
