config:
  # The name of the SUT  
  sut: "toystore"
  namespace: "toystore"
  sut_git_repo: "https://github.com/clue2-sose25/sustainable_toystore"
  sut_path: "toystore"
  helm_chart_path: "toystore/toystore"
  values_yaml_name: "values.yaml"
  target_service_name: "teastore-webui" # The k8s service name (used for in-cluster communication)
  application_endpoint_path: "/tools.descartes.teastore.webui" # The specific path
  default_resource_limits:
    cpu: 1000
    memory: 1024
  wait_before_workloads: 10
  wait_after_workloads: 10

helm_replacements:
  - value: "ghcr.io/clue2-sose25/sustainable_toystore"
    replacement: "registry:5000/clue"

workloads:
  - name: "shaped"
    description: "Workload with custom load shape behavior."
    timeout_duration: 120
    workload_settings: {}

variants:
  - name: "main"
    description: "Baseline experiment for the toystore application"
    target_branch: "main"
    colocated_workload: true
    critical_services: ["toystore-frontend", "toystore-backend"]
    autoscaling: "cpu"
