# Backend configuration
backend:
  image:
    repository: ghcr.io/clue2-sose25/sustainable_toystore/backend
    tag: "latest"
  replicas: 1
  service:
    port: 5000

# Frontend configuration
frontend:
  image:
    repository: ghcr.io/clue2-sose25/sustainable_toystore/frontend
    tag: "latest"
  replicas: 1
  service:
    port: 80

# Database configuration
database:
  name: toystore
  user: toystore_user
  password: toystore_password
