name: Build and Push Backend Image

on:
  push:
    branches:
      - main
      - baseline
      - postgres
    paths:
      - "backend/**"

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/clue2-sose25/sustainable_toystore/backend:latest
            ghcr.io/clue2-sose25/sustainable_toystore/backend:${{ github.sha }}
