name: Run CLUE2

on:
  push:
    branches:
      # Disabled for any existing branch. Use 'clue-helm.yml' instead.
      # This action is kept as an example of running CLUE in CI-CD pipelines outside the K8s cluster.
      # - baseline
      # - postgres
      - main

jobs:
  build:
    permissions:
      packages: write
      contents: read 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Runs CLUE2 as a docker container
        uses: clue2-sose25/Clue2/.github/actions/clue-docker@main
        with:
          clue-config-path: ./clue/clue-config.yaml
          sut-config-path: ./clue/toystore-config.yaml
          variants-name: baseline
          WORKLOADS: shaped