name: Run CLUE2

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Runs CLUE to test the ...
        uses: clue2-sose25/Clue2/.github/actions/clue-deploy@v1
        with:
          clue-config-path: ./clue/clue-config.yaml
          sut-cofig-path: ./clue/toystore-config.yaml
          image-registry: ghcr.io/clue2-sose25/sustainable_toystore
          cluster-config: {{ SECRETS.CLUSTER_CONFIG }}
          variant-name: {{ GITHUB.branch_name }}
          # threshold: total_energy_consuption > 500