name: Run CLUE2

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      packages: write
      contents: read 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Reconstruct SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TU_CLUSTER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Runs CLUE to test the ... 
        uses: clue2-sose25/Clue2/.github/actions/clue-deployer@githubActions-ExternCluster
        with:
          clue-config-path: ./clue/clue-config.yaml
          sut-config-path: ./clue/toystore-config.yaml
          image-registry: ghcr.io/clue2-sose25/sustainable_toystore
          variants-name: main
          CLUSTER_PROXY_COMMAND: ${{ github.CLUSTER_PROXY_COMMAND }}
          SSH_KEY_FILE_PATH:  "~/.ssh/id_rsa"
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          
          #threshold: total_energy_consuption > 500
