---
name: Test Helm Deploy

on:
  pull_request:
    paths:
      - 'clue_helm/**'
      - '.github/actions/clue-deployer/helm-action.yaml'
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Reconstruct SSH key 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TU_CLUSTER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: using kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 400 $HOME/.kube/config

      - name: Tunnel SSH
        run: ssh "${{ vars.CLUSTER_PROXY_COMMAND }}" -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no &
        
      - name: Wait for SSH tunnel
        run: sleep 5
      - name: using kubeconfig
        run: |
          kubectl cluster-info

  manual-approval:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    needs:
      - testing
    steps:
      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.actor }}
          exclude-workflow-initiator-as-approver: false
          fail-on-denial: true
        timeout-minutes: 5

  helm_deploy:
    runs-on: ubuntu-latest
    needs: 
      - manual-approval
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Reconstruct SSH key 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TU_CLUSTER_SSH_KEY }}" > ~/.ssh/id_rsa 
          chmod 400 ~/.ssh/id_rsa
      - name: using kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 400 $HOME/.kube/config

      - name: Tunnel SSH
        run: ssh "${{ vars.CLUSTER_PROXY_COMMAND }}" -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no &
        
      - name: Wait for SSH tunnel
        run: sleep 5

      - name: Deploy CLUE2 with Helm action
        uses: clue2-sose25/Clue2/.github/actions/clue-helm@v0
        with:
          kubeconfig-base64:: ${{ secrets.KUBE_CONFIG }}
          chart-path: clue_helm
          release-name: clue
          values-file: clue_helm/values-toystore.yaml
          namespace: st-cp25clue2
          results-path: clue_results
          helm-driver: configmap
          timeout-seconds: 450